# generated by scripts/copy_root_outputs.py

output "raw" {
  description = "Raw case"
  value       = module.case.raw
}

output "lower" {
  description = "lower case"
  value       = module.case.lower
}

output "upper" {
  description = "UPPER CASE"
  value       = module.case.upper
}

output "snake" {
  description = "snake_case"
  value       = module.case.snake
}

output "kebab" {
  description = "kebab-case"
  value       = module.case.kebab
}

output "pascal" {
  description = "PascalCase"
  value       = module.case.pascal
}

output "camel" {
  description = "camelCase"
  value       = module.case.camel
}

output "title" {
  description = "Title Case"
  value       = module.case.title
}

output "env_var" {
  description = "ENV_VAR_CASE"
  value       = module.case.env_var
}

output "alpha_num" {
  description = "AlphaNumCase"
  value       = module.case.alpha_num
}
